core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('example.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/urls.py
from django.urls import path

from . import views

app_name='example'

urlpatterns = [ 
    path('', views.index, name="homepage"),
    path('register', views.register, name="register"),
    path('my-login', views.my_login, name="my-login"),
    path('user-logout', views.user_logout, name='user-logout'),
    path('dashboard', views.my_dashboard, name="dashboard"),
    path('profile-management', views.profile_management, name="profile-management"),
    path('delete-conta', views.delete_conta, name='delete-conta')
]

example/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Profile(models.Model):    
    profile_pic = models.ImageField(upload_to='images/', null=True, blank=True, default='images/avatar.png')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.user.username

example/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput, TextInput

from .models import Profile


#user registration
class CreateUserForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

class UpdateUserForm(forms.ModelForm):
    password = None
    class Meta:
        model = User
        fields = ['username', 'email']
        exclude = ['password1', 'password2']

class UpdateProfileForm(forms.ModelForm):
    profile_pic = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control-file'}))
    class Meta:
        model = Profile
        fields =  ['profile_pic']
      

example/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, auth
from django.shortcuts import redirect, render

from .forms import CreateUserForm, LoginForm, UpdateProfileForm, UpdateUserForm
from .models import Profile


# Create your views here.
def index(request):
    return render(request, 'example/homepage.html', {})


def register(request):
    form = CreateUserForm()
    if request.user.is_authenticated:
        return redirect('example:dashboard')
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        current_user = form.save(commit=False)
        form.save()
        profile = Profile.objects.create(user=current_user)
        return redirect('example:my-login')
    return render(request, 'example/register.html', {'form': form})

def my_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect("example:dashboard")
    
    return render(request, 'example/mylogin.html', {'form': form})
@login_required(login_url="example:my-login")
def my_dashboard(request):
    profile_pic = Profile.objects.get(user=request.user)
    return render(request, 'example/dashboard.html', {'profilePicture': profile_pic})

@login_required(login_url="example:my-login")
def profile_management(request):
    form = UpdateUserForm(instance=request.user)
    profile = Profile.objects.get(user=request.user)
    profile_form = UpdateProfileForm(instance=profile)

    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('example:dashboard')
        if profile_form.is_valid():
            profile_form.save()
            return redirect('example:dashboard')

    return render(request, 'example/profile-management.html', {'form': form, 'profile_form': profile_form, 'profile':profile})

def user_logout(request):
    auth.logout(request)
    return redirect("example:homepage")

@login_required(login_url="example:my-login")
def delete_conta(request):
    if request.method == "POST":
        deleteUser  = User.objects.get(username=request.user)
        deleteUser.delete()
        return redirect("example:homepage")
    
    return render(request, "example/deleteconta.html", {})


    

src/example/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, auth
from django.shortcuts import redirect, render

from .forms import CreateUserForm, LoginForm, UpdateProfileForm, UpdateUserForm
from .models import Profile


# Create your views here.
def index(request):
    return render(request, 'example/homepage.html', {})


def register(request):
    form = CreateUserForm()
    if request.user.is_authenticated:
        return redirect('example:dashboard')
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            return redirect('example:my-login')
    return render(request, 'example/register.html', {'form': form})

def my_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect("example:dashboard")
    
    return render(request, 'example/mylogin.html', {'form': form})
@login_required(login_url="example:my-login")
def my_dashboard(request):
    profile_pic = Profile.objects.get(user=request.user)
    return render(request, 'example/dashboard.html', {'profilePicture': profile_pic})

@login_required(login_url="example:my-login")
def profile_management(request):
    form = UpdateUserForm(instance=request.user)
    profile = Profile.objects.get(user=request.user)
    profile_form = UpdateProfileForm(instance=profile)

    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('example:dashboard')
        if profile_form.is_valid():
            profile_form.save()
            return redirect('example:dashboard')

    return render(request, 'example/profile-management.html', {'form': form, 'profile_form': profile_form, 'profile':profile})

def user_logout(request):
    auth.logout(request)
    return redirect("example:homepage")

@login_required(login_url="example:my-login")
def delete_conta(request):
    if request.method == "POST":
        deleteUser  = User.objects.get(username=request.user)
        deleteUser.delete()
        return redirect("example:homepage")
    
    return render(request, "example/deleteconta.html", {})


    

example/templates/example/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 justify-content-center">

    <a class="navbar-brand main-heading" href="{% url 'example:homepage' %}">

        &nbsp; Homepage

    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>

    </button>


    <div class="collapse navbar-collapse text-center" id="navbarNavDropdown">


        <ul class="navbar-nav ml-auto">


            &nbsp; &nbsp; &nbsp;

            {% if not user.is_authenticated %}
            <li class="nav-item">

                <a href="{% url 'example:register' %}">Register</a>

            </li>


            &nbsp; &nbsp; &nbsp;


            <li class="nav-item">

                <a href="{% url 'example:my-login' %}">Login</a>

            </li>


            &nbsp; &nbsp; &nbsp;
            {% else %}
            <li class="nav-item me-3">
                <a href="{% url 'example:dashboard' %}">Dashboard</a>
            </li>

            <li class="nav-item me-3">
                <a href="{% url 'example:profile-management' %}">Profile Management</a>
            </li>

            <li class="nav-item me-3">
                <a href="{% url 'example:user-logout' %}">Logout</a>
            </li>
            {% endif %}


        </ul>


    </div>


</nav>

example/templates/example/dashboard.html
{% extends './index.html'  %}

{% block title %}
Dashboard
{% endblock title %}


{% block content %}
<br>
<div class="container bg-white shaddow-md p-5 form-layout">
    <div class="row pb-3 ">
        <h1 class="fw-bold ">Dashboard</h1>
    </div>
    <div class="row">
        <h6 class="text-muted">&nbsp; &nbsp; &nbsp;Welcome {{user}}.</h6>
        <div class="col-3 text-center"><img style="width:100px" src="{{profilePicture.profile_pic.url}}"></div>
    </div>
</div>
<hr>
</div>

{% endblock content %}

example/templates/example/deleteconta.html
{% extends './index.html'  %}
{% load crispy_forms_tags %}


{% block title %}
Deletar conta
{% endblock title %}


{% block content %}

<div class="container bg-white shadow-md p-5 form-layout">
    <form autocomplete="off" method="POST">
        {% csrf_token %}
        <p> Do you really want to delete your account?</p>
        <br>
        <a class="btn btn-info" href="{% url 'example:profile-management' %}">Go back</a>
        <br>
        <br>

        <input class="btn btn-danger" href="{% url 'example:delete-conta' %}" value="Confirme account deletion"
            type="submit"></>
    </form>
</div>
{% endblock content %}

example/templates/example/homepage.html
{% extends 'example/index.html'  %}

{%block title %} Homepage {% endblock %}


{% block content %}

<br>

<br>
<br>

<div class="text-center">

    <h2> This.... is The best website out there! </h2>

    <br>
    <a class="btn btn-outline-primary" type="button" href="{% url 'example:register' %}">Register</a>

</div>


</body>
{% endblock content %}

example/templates/example/index.html
{% load static %}


<html>

<head>
  <title>{%block title %} Homepage {% endblock %}</title>

  <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/morph/bootstrap.min.css" />

  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
</head>

<body>
  {% include 'example/components/navbar.html' %}
  {% block content %}
  {% endblock content %}
  <script src="{% static 'js/app.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
  </script>

</html>

example/templates/example/mylogin.html
{% extends './index.html'  %}
{% load crispy_forms_tags %}


{% block title %}
My login
{% endblock title %}


{% block content %}


<div class="container bg-white shadow-md border border-3 form-layout mb-3 border-light p-5">
    <form method="POST" autocomplete="off">
        {% csrf_token %}
        {{form.username|as_crispy_field}}
        <br>
        {{form.password|as_crispy_field}}
        <br>
        <input value="login" type="submit" class="btn btn-primary w-100">
    </form>
    <br>
    <p>Dont you have an account?</p> <a href="{% url 'example:register' %}">Register your account.</a>
</div>

{% endblock content %}

example/templates/example/profile-management.html
{% extends './index.html'  %}
{% load crispy_forms_tags %}
{% block title %}
profile management
{% endblock title %}


{% block content %}
<div class="container bg-white shadow-md border border-3 form-layout mb-3 border-light p-5">
    <h1 class="text-center">Update username and email</h1>
    <form method="POST" autocomplete="off">
        {% csrf_token %}
        {{form.username|as_crispy_field}}
        <br>
        {{form.email|as_crispy_field}}
        <br>
        <input value="Update" type="submit" class="btn btn-primary w-100">
    </form>
</div>
<div class="container text-center bg-white shadow-md border border-3 form-layout mb-3 border-light p-5">
    <h2 class="text-center">Upload your Profile Picture</h2>
    <br>
    <img style="width:100px" src="{{profile.profile_pic.url}}" alt="user_picture">
    <br>
    <br>
    <form method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        {{profile_form.profile_pic|as_crispy_field}}
        <br>
        <input value="Upload" type="submit" class="btn btn-primary w-100">
    </form>
</div>
<div class="container bg-white shadow-md border border-3 form-layout mb-3 border-light p-5">
    <h3>Account Deletion</h3>
    <a href="{% url 'example:delete-conta' %}">Delete account?</a>
</div>
{% endblock content %}

example/templates/example/register.html
{% extends './index.html'  %}
{% load crispy_forms_tags %}

{% block title %}
register
{% endblock title %}


{% block content %}
<div class="container bg-white shadow-md border border-3 form-layout mb-3 border-light p-5">
    <h1>Register</h1>
    <br>
    <form method="POST" autocomplete="off">
        {% csrf_token %}

        {{form.username|as_crispy_field}}
        <br>
        {{form.email|as_crispy_field}}
        <br>
        {{form.password1|as_crispy_field}}
        <br>
        {{form.password2|as_crispy_field}}
        <br>
        <input class="btn btn-primary w-100" type="submit" value="Register">
    </form>
    <br>
    <p>Alreay have an account?</p> <a href="{% url 'example:my-login' %}">Login to my account.</a>
</div>

{% endblock content %}